services:
  # Backend API Service
  - type: web
    name: student-management-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://student-management-frontend.onrender.com
    disk:
      name: uploads
      mountPath: /app/backend/uploads
      sizeGB: 1

  # Frontend Static Site
  - type: web
    name: student-management-frontend
    env: static
    buildCommand: cd student-management-frontend && npm install && npm run build
    staticPublishPath: student-management-frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://student-management-backend.onrender.com

databases:
  # SQLite is file-based, so we'll use the disk storage above
  # For production, consider upgrading to PostgreSQL:
  # - name: student-management-db
  #   databaseName: student_management
  #   user: admin
